# mysql-dev.yaml  (dev-only, ephemeral storage)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubeflow
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "mlpipeline"
            - name: MYSQL_USER
              value: "mlflow"
            - name: MYSQL_PASSWORD
              value: "mlflow"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
---
# ensure Service exists (won't break if already present)
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kubeflow
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

