apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-yt-ingest-10gi
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/yt-ingest
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - large
  claimRef:
    namespace: mlops
    name: yt-ingest-data-pvc

