apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yt-ingest-data-pvc
  namespace: mlops
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: Service
metadata:
  name: yt-ingest-svc
  namespace: mlops
spec:
  selector:
    app: yt-ingest
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-ingest
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-ingest
  template:
    metadata:
      labels:
        app: yt-ingest
    spec:
      serviceAccountName: fastapi-sa
      nodeSelector:
        role: large
      tolerations:
        - key: "dedicated"
          operator: "Exists"
          effect: "NoSchedule"
      securityContext:
        fsGroup: 1000
      containers:
        - name: yt-ingest
          image: 118730128420.dkr.ecr.us-east-1.amazonaws.com/yt-ingest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: S3_BUCKET
              value: mlops-yt-artifacts-nandak-1760367211
            - name: S3_PREFIX
              value: datasets
            - name: AWS_REGION
              value: us-east-1
            - name: LOCAL_OUT
              value: /data/youtube_comments.csv
          volumeMounts:
            - name: yt-ingest-data
              mountPath: /data
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: yt-ingest-data
          persistentVolumeClaim:
            claimName: yt-ingest-data-pvc

